POST http://localhost:3333/videos
Content-Type: application/json
//Requisição - meta dados
//Enviando...

{
    "title": "Vídeo 01",
    "description": "Primeiro vídeo",
    "duration": 180
}

###

GET  http://localhost:3333/videos
